#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace IPPS.CaseManagement.Models
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class DataverseServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public DataverseServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="IPPS.CaseManagement.Models.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<IPPS.CaseManagement.Models.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<IPPS.CaseManagement.Models.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="IPPS.CaseManagement.Models.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<IPPS.CaseManagement.Models.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<IPPS.CaseManagement.Models.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="IPPS.CaseManagement.Models.ipps_case"/> entities.
		/// </summary>
		public System.Linq.IQueryable<IPPS.CaseManagement.Models.ipps_case> ipps_caseSet
		{
			get
			{
				return this.CreateQuery<IPPS.CaseManagement.Models.ipps_case>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="IPPS.CaseManagement.Models.ipps_customconfiguration"/> entities.
		/// </summary>
		public System.Linq.IQueryable<IPPS.CaseManagement.Models.ipps_customconfiguration> ipps_customconfigurationSet
		{
			get
			{
				return this.CreateQuery<IPPS.CaseManagement.Models.ipps_customconfiguration>();
			}
		}
	}
}
#pragma warning restore CS1591
