#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPS.CaseManagement.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum ipps_prioritycodes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 141860000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 141860001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 141860002,
	}
}
#pragma warning restore CS1591
