#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPPS.CaseManagement.Models
{
	
	
	/// <summary>
	/// Status of the Case
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum ipps_case_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Case
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum ipps_case_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 141860001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnHold = 141860002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 141860003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 141860004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ipps_case")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class ipps_case : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the ipps_case entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ipps_assignedto = "ipps_assignedto";
			public const string ipps_caseId = "ipps_caseid";
			public const string Id = "ipps_caseid";
			public const string ipps_casenumber = "ipps_casenumber";
			public const string ipps_customerid = "ipps_customerid";
			public const string ipps_description = "ipps_description";
			public const string ipps_name = "ipps_name";
			public const string ipps_Priority = "ipps_priority";
			public const string ipps_resolution = "ipps_resolution";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string ipps_ipps_case_account_ipps_customerid = "ipps_ipps_case_account_ipps_customerid";
			public const string ipps_ipps_case_contact_ipps_customerid = "ipps_ipps_case_contact_ipps_customerid";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ipps_case() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "ipps_case";
		
		public const string EntityLogicalCollectionName = "ipps_cases";
		
		public const string EntitySetName = "ipps_cases";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_assignedto")]
		public string ipps_assignedto
		{
			get
			{
				return this.GetAttributeValue<string>("ipps_assignedto");
			}
			set
			{
				this.OnPropertyChanging("ipps_assignedto");
				this.SetAttributeValue("ipps_assignedto", value);
				this.OnPropertyChanged("ipps_assignedto");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_caseid")]
		public System.Nullable<System.Guid> ipps_caseId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ipps_caseid");
			}
			set
			{
				this.OnPropertyChanging("ipps_caseId");
				this.SetAttributeValue("ipps_caseid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ipps_caseId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_caseid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ipps_caseId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_casenumber")]
		public string ipps_casenumber
		{
			get
			{
				return this.GetAttributeValue<string>("ipps_casenumber");
			}
			set
			{
				this.OnPropertyChanging("ipps_casenumber");
				this.SetAttributeValue("ipps_casenumber", value);
				this.OnPropertyChanged("ipps_casenumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_customerid")]
		public Microsoft.Xrm.Sdk.EntityReference ipps_customerid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipps_customerid");
			}
			set
			{
				this.OnPropertyChanging("ipps_customerid");
				this.SetAttributeValue("ipps_customerid", value);
				this.OnPropertyChanged("ipps_customerid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_description")]
		public string ipps_description
		{
			get
			{
				return this.GetAttributeValue<string>("ipps_description");
			}
			set
			{
				this.OnPropertyChanging("ipps_description");
				this.SetAttributeValue("ipps_description", value);
				this.OnPropertyChanged("ipps_description");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_name")]
		public string ipps_name
		{
			get
			{
				return this.GetAttributeValue<string>("ipps_name");
			}
			set
			{
				this.OnPropertyChanging("ipps_name");
				this.SetAttributeValue("ipps_name", value);
				this.OnPropertyChanged("ipps_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_priority")]
		public virtual ipps_prioritycodes? ipps_Priority
		{
			get
			{
				return ((ipps_prioritycodes?)(EntityOptionSetEnum.GetEnum(this, "ipps_priority")));
			}
			set
			{
				this.OnPropertyChanging("ipps_Priority");
				this.SetAttributeValue("ipps_priority", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipps_Priority");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_resolution")]
		public string ipps_resolution
		{
			get
			{
				return this.GetAttributeValue<string>("ipps_resolution");
			}
			set
			{
				this.OnPropertyChanging("ipps_resolution");
				this.SetAttributeValue("ipps_resolution", value);
				this.OnPropertyChanged("ipps_resolution");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual ipps_case_statecode? statecode
		{
			get
			{
				return ((ipps_case_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual ipps_case_statuscode? statuscode
		{
			get
			{
				return ((ipps_case_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 ipps_ipps_case_account_ipps_customerid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipps_ipps_case_account_ipps_customerid")]
		public IPPS.CaseManagement.Models.Account ipps_ipps_case_account_ipps_customerid
		{
			get
			{
				return this.GetRelatedEntity<IPPS.CaseManagement.Models.Account>("ipps_ipps_case_account_ipps_customerid", null);
			}
			set
			{
				this.OnPropertyChanging("ipps_ipps_case_account_ipps_customerid");
				this.SetRelatedEntity<IPPS.CaseManagement.Models.Account>("ipps_ipps_case_account_ipps_customerid", null, value);
				this.OnPropertyChanged("ipps_ipps_case_account_ipps_customerid");
			}
		}
		
		/// <summary>
		/// N:1 ipps_ipps_case_contact_ipps_customerid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipps_customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipps_ipps_case_contact_ipps_customerid")]
		public IPPS.CaseManagement.Models.Contact ipps_ipps_case_contact_ipps_customerid
		{
			get
			{
				return this.GetRelatedEntity<IPPS.CaseManagement.Models.Contact>("ipps_ipps_case_contact_ipps_customerid", null);
			}
			set
			{
				this.OnPropertyChanging("ipps_ipps_case_contact_ipps_customerid");
				this.SetRelatedEntity<IPPS.CaseManagement.Models.Contact>("ipps_ipps_case_contact_ipps_customerid", null, value);
				this.OnPropertyChanged("ipps_ipps_case_contact_ipps_customerid");
			}
		}
	}
}
#pragma warning restore CS1591
